export const models = [
  "Systran/faster-whisper-large-v3",
  "Systran/faster-whisper-medium",
  "Systran/faster-whisper-base",
  "Systran/faster-whisper-small",
  "Systran/faster-whisper-tiny",
  "Systran/faster-distil-whisper-large-v3",
  "Systran/faster-distil-whisper-medium.en",
  "Systran/faster-distil-whisper-small.en",
  "Systran/faster-distil-whisper-large-v2",
  "Systran/faster-whisper-large-v2",
  "Systran/faster-whisper-large-v1",
  "Systran/faster-whisper-medium.en",
  "Systran/faster-whisper-base.en",
  "Systran/faster-whisper-small.en",
  "Systran/faster-whisper-tiny.en",
];

export const languageOptions: Record<string, string> = {
  en: "english",
  zh: "chinese",
  de: "german",
  es: "spanish",
  ru: "russian",
  ko: "korean",
  fr: "french",
  ja: "japanese",
  pt: "portuguese",
  tr: "turkish",
  pl: "polish",
  ca: "catalan",
  nl: "dutch",
  ar: "arabic",
  sv: "swedish",
  it: "italian",
  id: "indonesian",
  hi: "hindi",
  fi: "finnish",
  vi: "vietnamese",
  he: "hebrew",
  uk: "ukrainian",
  el: "greek",
  ms: "malay",
  cs: "czech",
  ro: "romanian",
  da: "danish",
  hu: "hungarian",
  ta: "tamil",
  no: "norwegian",
  th: "thai",
  ur: "urdu",
  hr: "croatian",
  bg: "bulgarian",
  lt: "lithuanian",
  la: "latin",
  mi: "maori",
  ml: "malayalam",
  cy: "welsh",
  sk: "slovak",
  te: "telugu",
  fa: "persian",
  lv: "latvian",
  bn: "bengali",
  sr: "serbian",
  az: "azerbaijani",
  sl: "slovenian",
  kn: "kannada",
  et: "estonian",
  mk: "macedonian",
  br: "breton",
  eu: "basque",
  is: "icelandic",
  hy: "armenian",
  ne: "nepali",
  mn: "mongolian",
  bs: "bosnian",
  kk: "kazakh",
  sq: "albanian",
  sw: "swahili",
  gl: "galician",
  mr: "marathi",
  pa: "panjabi",
  si: "sinhala",
  km: "khmer",
  sn: "shona",
  yo: "yoruba",
  so: "somali",
  af: "afrikaans",
  oc: "occitan",
  ka: "georgian",
  be: "belarusian",
  tg: "tajik",
  sd: "sindhi",
  gu: "gujarati",
  am: "amharic",
  yi: "yiddish",
  lo: "lao",
  uz: "uzbek",
  fo: "faroese",
  ht: "haitian",
  ps: "pashto",
  tk: "turkmen",
  nn: "norwegianNynorsk",
  mt: "maltese",
  sa: "sanskrit",
  lb: "luxembourgish",
  my: "burmese",
  bo: "tibetan",
  tl: "tagalog",
  mg: "malagasy",
  as: "assamese",
  tt: "tatar",
  haw: "hawaiian",
  ln: "lingala",
  ha: "hausa",
  ba: "bashkir",
  jw: "jw",
  su: "sundanese",
  yue: "yueChinese",
};

export const getTranslatedLanguageOptions = (dictionary: any) => {
  return Object.fromEntries(
    Object.entries(languageOptions).map(([key, value]) => [key, dictionary[value]])
  );
};
